207 pinpoint server implementation
robertvo824/analytics pull request #1
Opened 2021-09-15 18:58 UTC by robertvo824

## Status

WIP

## Description

- Working state of `@analytics/aws-pinpoint` to send custom events from `Node.js` to `AWS Pinpoint`.
- Still refactoring, moving things around, and cleaning unnecessary logic

2021-09-16 20:48 UTC, robertvo824 commented
@rgwozdz 

- Moved helpers into separate directory
- Created one Pinpoint `index.js` file (without having a `browser.js` and `node.js`)
    - Created one Pinpoint `call-aws.js` file that handles the creation of aws-client using `aws4fetch` or `aws-sdk` depending on `inBrowser`

2021-09-22 20:44 UTC, rgwozdz requested changes
This is excellent work Bob.  Great job extracting shared code to helpers!  There may be a few more opportunities for that, see my comments.

Are there no tests for the original browser code?  Seems like we'd want to make sure the new node pieces are under test.

2021-09-22 20:44 UTC, rgwozdz commented on packages/analytics-plugin-aws-pinpoint/src/node.js
> +      }
I notice in browser.js at this location, there is a block:
```
      if (traits.email) {
        ;(endpoint.Address = traits.email),
          (endpoint.ChannelType = CHANNEL_TYPES.EMAIL)
      }
```
why was that removed from the node.js version?

2021-09-22 20:44 UTC, rgwozdz commented on packages/analytics-plugin-aws-pinpoint/src/node.js
> +function formatEventData(obj) {
I think this could be shared code; appears in browser.js too

2021-09-22 20:44 UTC, rgwozdz commented on packages/analytics-plugin-aws-pinpoint/src/node.js
> +function loadError() {
I think this could be shared code, appears in browser.js too.

2021-09-22 20:44 UTC, rgwozdz commented on packages/analytics-plugin-aws-pinpoint/src/node.js
> +      /* If anonId has changed, refresh session details */
Add line of whitespace

2021-09-22 20:44 UTC, rgwozdz commented on packages/analytics-plugin-aws-pinpoint/src/node.js
> +    bootstrap: (pluginApi) => {
I think this could be shared code, appears in browser.js too.

2021-09-27 10:03 UTC, robertvo824 commented on packages/analytics-plugin-aws-pinpoint/src/node.js
> +function formatEventData(obj) {
Good call. This was the first file I touched so I didn't event think about sharing code early on.

2021-09-27 10:19 UTC, robertvo824 commented
> Are there no tests for the original browser code? Seems like we'd want to make sure the new node pieces are under test.

That is correct. It appears that he lacks tests for all of the individual plugins (browser and node), but contains tests for `analytics-core` and his `utils` which I believe are supposed to cover any and all plugins that are added. For example, this is the file for server-side test in `analytics-core` https://github.com/DavidWells/analytics/blob/master/packages/analytics-core/tests/api-serverside.test.js.

2021-09-27 13:30 UTC, rgwozdz commented
On tests...ok, that's pretty wild.  To me that means you can submit your fork back to the main repo and see what the response is.  I do think we need a follow up task to put everything under test.

2021-09-27 19:08 UTC, robertvo824 commented on packages/analytics-plugin-aws-pinpoint/src/node.js
> +      }
Sorry, forgot to reply to this comment. That was from my initial attempt at getting it to work in Node. I didn't want to focus on email at the time. I will go ahead and add it back in when I pull out some shared code.

2021-09-28 14:44 UTC, robertvo824 commented
Made requested changes:

- Moved shared logic for loadError, formatEventData, and bootstrap into separate modules
- Added line of whitespace
- Fixed `session_start is undefined` error in `create-pinpoint-sender.js`

2021-09-28 16:16 UTC, robertvo824 commented
Closing this out and made a new PR on the original repo.

https://github.com/DavidWells/analytics/pull/217

2021-09-28 16:16 UTC, closed without merging